<a href="https://colab.research.google.com/github/doraem-on/MLSC-hackathon/blob/main/ML_lab_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,6,4,5])

rev = arr[::-1]
print(rev)

[5 4 6 3 2 1]


In [2]:
import numpy as np
arr1 = np.array([[1,2,3] , [2,4,5] , [1,2,3]])
flat1 = arr1.flatten()
rev1 = arr1.ravel()
print(flat1)
print(rev1)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [5]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
val , count = np.unique(x , return_counts=True)
print(val)
print(count)
freq = np.argmax(count)
final = val[freq]
print(final)

[1 2 3 4 5]
[5 2 1 1 1]
1


In [6]:
import numpy as np
mat = np.matrix('[4,1,9; 12,3,1; 4,5,6]')
stum = np.sum(mat)
rsum = np.sum(mat , axis=1)
csum = np.sum(mat , axis = 0)
print(stum)
print(rsum)
print(csum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [9]:
import numpy as np

mat2 = np.array([[55,25] , [11 , 45]])
dsum = np.trace(mat2)
eigenvalues, eigenvectors = np.linalg.eig(mat2)
minv = np.linalg.inv(mat2)

mdet = np.linalg.det(mat2)
print(dsum)
print(eigenvalues)
print(eigenvectors)
print(minv)
print(mdet)

100
[67.32050808 32.67949192]
[[ 0.89698839 -0.74595131]
 [ 0.44205411  0.66600049]]
[[ 0.02045455 -0.01136364]
 [-0.005       0.025     ]]
2200.0000000000014


In [12]:
import numpy as np
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])
mul = np.dot(p1,q1)
cov = np.cov(p1.ravel(),q1.ravel())
print(mul)
print(cov)

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [14]:
import numpy as np
import itertools
x = np.array ([[2,3,4] , [3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
inner_prod = np.inner(x,y)
outer_prod = np.outer(x,y)
cartesian = list(itertools.product(x.ravel(),y.ravel()))
print(inner_prod)
print(outer_prod)
print(cartesian[:5])
print(cartesian[-5:])

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[(np.int64(2), np.int64(1)), (np.int64(2), np.int64(5)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(5)), (np.int64(2), np.int64(10))]
[(np.int64(9), np.int64(5)), (np.int64(9), np.int64(0)), (np.int64(9), np.int64(5)), (np.int64(9), np.int64(10)), (np.int64(9), np.int64(3))]


In [16]:
import numpy as np
array = np.array([[1,-2,3], [-4,5,-6]])
abs_val= np.abs(array)
print(abs_val)
parr = np.percentile(array , [25,50,75])
pcol = np.percentile(array , [25,50,75] , axis=0)
prow = np.percentile(array , [25,50,75] , axis=1)
print(parr)
print(pcol)
print(prow)
xf , mf , stf = np.mean(array) , np.median(array) , np.std(array)
print(xf , mf , stf)

[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224


In [17]:
import numpy as np
a = np.array([-1.8 , -1.6, -0.5 , 0.5 , 1.6 , 1.8 , 3.0])
np.floor(a)
np.ceil(a)
np.trunc(a)
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

In [19]:
import numpy as np
array = np.array([10,52,62,16,16,54,453])
s_arr = np.sort(array)
ind_arr=np.argsort(array)

s_4_smallest = s_arr[:4]

l_5_largest = s_arr[-5:]
print("Sorted Array:", s_arr)
print("Indices of Sorted Array:", ind_arr)
print("4 Smallest Elements:", s_4_smallest)
print("5 Largest Elements:", l_5_largest)

Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]


In [20]:
import numpy as np
arr = np.array([1.0 , 1.2 , 2.2 , 2.0 , 3.0 , 2.0])
int_only = array[array % 1 == 0]
flo_only = array[array % 1 != 0]
print(flo_only)
print(int_only)

[]
[ 10  52  62  16  16  54 453]
